server:
  port: 8080

spring:
  application:
    name: bankcards
  datasource:
    url: jdbc:postgresql://localhost:5432/bankcards
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

Что нужно сделать:
  - Настроить параметры безопасности и JWT.
  - Включить Swagger UI.
