server:
  port: 8080

spring:
  application:
    name: bankcards
  datasource:
    url: jdbc:postgresql://localhost:5432/bankcards
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    jwt:
      secret: vdeNR3G2uMdCQD3vY3O1Z7vjBoBN4Uv3UwGM+2P3kZQ=
      issuer: bankcards-api
      access-ttl-minutes: 60
      header: auth-token


Что нужно сделать:
  - Настроить параметры безопасности и JWT.
  - Включить Swagger UI.
